package com.example.connectme

//data class Message(
//    val text: String,
//    val isSender: Boolean,  // true if the message is sent by the user, false if received
//    val time: String        // Add time for the messages
//)

data class Message(
    var id: String = "",            // Unique message ID (could be generated by Firebase)
    var text: String? = null,       // Message text
    var imageUrl: String? = null,   // URL if message contains an image
    var isSender: Boolean = false,  // True if the current user sent the message
    var time: Long = 0L,       // When message was sent
    var lastEdited: Long? = null,   // Last time edited (if applicable)
    var isRead: Boolean = false     // For vanish mode: becomes true when seen
)
